### ISSUE TITLE
Avoid using case ranges in switch statements

### ISSUE THREAD

**Issue by gieseanw** [binji/smolnes#2]
Code like `case 6 ... 7` is a GNU extension and not standard C++. Replacing with fall through blocks will help get this code to work on more platforms.

**Comment by binji** [comment]
It would be nice, but removing case ranges makes the code quite a bit larger. I might be able to figure out how to shrink it down again, but then I'd have to reformat everything anyway. In the meantime I mention that fact that it's required in the README.
