### ISSUE TITLE
Errors compiling on mac

### ISSUE THREAD

**Issue by lukeboi** [binji/smolnes#5]
Hi!

I'm trying to compile smolnes on MacOS version 12.0.1, Apple Silicon. I'm getting this error:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/9501933/203454833-ac909a71-58f2-4032-aa99-5458a652e82f.png">

My gcc version:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/9501933/203454878-ce91a493-a36d-45ab-9dba-ca7ee3993ee2.png">

Any ideas?

**Comment by binji** [comment]
Oh, I suppose technically I can't remove that parameter name until C2x, but it seems that your compiler is treating it as an error instead. I'll see if I can put the name back in so it is more compatible.

**Comment by binji** [comment]
I just pushed 9083985c7c74e61ffba66bbd8f274cbf9600306c which should fix this.

**Comment by lukeboi** [comment]
Now compiles without issue. Thank you so much!
